import { eventBus } from './event_bus';
import { auditLog } from './audit_log';
import type { GhostMartPackage } from './ghost_mart_package';
import { ghostMartPackageStore } from './ghost_mart_package';
import { workspaceInstallStore } from './ghost_mart_workspace_install';
import type { WorkerBackendManifest } from './worker_backend_manifest';
import type { WorkerBackendRegistry } from './worker_backend_manifest';
import type { BlueprintLaunchReadinessChecker } from './blueprint_launch_readiness';

// ── Launch Step Types ──────────────────────────────────────────────────────

/**
 * BlueprintLaunchStepType — the kind of action a launch step represents.
 */
export type BlueprintLaunchStepType =
  | 'install_package'
  | 'enable_package'
  | 'create_agent'
  | 'seed_signal'
  | 'initialize_memory'
  | 'initialize_workspace_resource';

/**
 * BlueprintLaunchStep — a single discrete action in a blueprint launch plan.
 *
 * Steps are ordered and intended for sequential execution through the
 * Signal → Plan → Job pipeline.  The planner only generates steps —
 * it does NOT execute them.
 */
export type BlueprintLaunchStep = {
  /** Unique step identifier within the launch plan. */
  step_id: string;
  /** What kind of action this step performs. */
  step_type: BlueprintLaunchStepType;
  /** Human-readable description of the step. */
  description: string;
  /** The package_id this step operates on (if applicable). */
  package_id: string | null;
  /** Capabilities required to execute this step. */
  required_capabilities: string[];
  /** Number of jobs this step is expected to generate when executed. */
  jobs_to_create: number;
};

// ── Launch Plan ────────────────────────────────────────────────────────────

/**
 * BlueprintLaunchPlan — a structured, ordered plan for launching a blueprint
 * in a workspace.  Generated by BlueprintLaunchPlanner and intended for
 * later execution through the existing Signal → Plan → Job pipeline.
 */
export type BlueprintLaunchPlan = {
  /** Globally unique identifier for this launch plan. */
  launch_id: string;
  /** The blueprint package_id this plan launches. */
  blueprint_id: string;
  /** The workspace this plan targets. */
  workspace_id: string;
  /** Ordered list of steps to execute. */
  steps: BlueprintLaunchStep[];
  /** All packages required by the blueprint (transitive). */
  required_packages: string[];
  /** Compatible backends available for this launch. */
  required_backends: WorkerBackendManifest[];
  /** Total estimated jobs across all steps. */
  estimated_jobs: number;
  /** Whether a readiness check passed before planning. */
  readiness_passed: boolean;
  /** Failure reasons from readiness check (empty if passed). */
  readiness_failures: string[];
};

// ── Planner ────────────────────────────────────────────────────────────────

let _nextPlanId = 1;
function nextPlanId(): string {
  return `launch_plan_${_nextPlanId++}`;
}

let _nextStepId = 1;
function nextStepId(): string {
  return `launch_step_${_nextStepId++}`;
}

let _nextPlannerAuditId = 1;
function nextPlannerAuditId(): string {
  return `audit_blp_${_nextPlannerAuditId++}`;
}

/**
 * BlueprintLaunchPlanner — converts a blueprint into a structured launch plan.
 *
 * The planner inspects the blueprint's dependency tree, determines which
 * packages need to be installed or enabled, which agents need to be created,
 * and what initial signals/resources must be seeded.  It produces an ordered
 * list of BlueprintLaunchSteps but does NOT execute any of them.
 *
 * Optionally integrates with BlueprintLaunchReadinessChecker to validate
 * that the workspace meets all prerequisites before generating the plan.
 */
export class BlueprintLaunchPlanner {
  constructor(
    private readonly backendRegistry: WorkerBackendRegistry,
    private readonly readinessChecker?: BlueprintLaunchReadinessChecker,
  ) {}

  /**
   * Generate a launch plan for a blueprint in a workspace.
   *
   * Steps are generated in dependency-safe order:
   *   1. install_package  — for packages not yet installed
   *   2. enable_package   — for packages installed but not enabled
   *   3. create_agent     — for agent-type packages
   *   4. initialize_workspace_resource — workspace-level setup
   *   5. initialize_memory — memory/state initialization
   *   6. seed_signal      — the initial signal that kicks off the blueprint
   */
  createLaunchPlan(
    blueprintId: string,
    workspaceId: string,
  ): BlueprintLaunchPlan {
    const blueprint = ghostMartPackageStore.getById(blueprintId);

    // Validate blueprint exists and is correct type
    if (!blueprint || blueprint.package_type !== 'blueprint') {
      const plan: BlueprintLaunchPlan = {
        launch_id: nextPlanId(),
        blueprint_id: blueprintId,
        workspace_id: workspaceId,
        steps: [],
        required_packages: [],
        required_backends: [],
        estimated_jobs: 0,
        readiness_passed: false,
        readiness_failures: [
          blueprint
            ? `Package '${blueprintId}' is type '${blueprint.package_type}', not 'blueprint'.`
            : `Blueprint '${blueprintId}' not found in package store.`,
        ],
      };
      this.emitCreated(plan);
      return plan;
    }

    // Run readiness check if checker is available
    let readinessPassed = true;
    let readinessFailures: string[] = [];
    if (this.readinessChecker) {
      const readiness = this.readinessChecker.validateBlueprintLaunchReadiness(
        blueprintId,
        workspaceId,
      );
      readinessPassed = readiness.ready;
      readinessFailures = readiness.failure_reasons;
    }

    // Collect all required packages (topological order via dependency walk)
    const requiredPackages = this.collectRequiredPackages(blueprint);

    // Find compatible backends
    const compatibleBackends = this.findCompatibleBackends(workspaceId);

    // Generate steps
    const steps: BlueprintLaunchStep[] = [];

    // Phase 1: Install missing packages (skills first, then agents)
    const skillsToInstall = this.getPackagesToInstall(requiredPackages, workspaceId, 'skill');
    const agentsToInstall = this.getPackagesToInstall(requiredPackages, workspaceId, 'agent');

    for (const pkg of [...skillsToInstall, ...agentsToInstall]) {
      steps.push({
        step_id: nextStepId(),
        step_type: 'install_package',
        description: `Install ${pkg.package_type} '${pkg.name}' (${pkg.package_id}) into workspace '${workspaceId}'.`,
        package_id: pkg.package_id,
        required_capabilities: [],
        jobs_to_create: 1,
      });
    }

    // Phase 2: Enable packages that are installed but not enabled
    const skillsToEnable = this.getPackagesToEnable(requiredPackages, workspaceId, 'skill');
    const agentsToEnable = this.getPackagesToEnable(requiredPackages, workspaceId, 'agent');

    for (const pkg of [...skillsToEnable, ...agentsToEnable]) {
      steps.push({
        step_id: nextStepId(),
        step_type: 'enable_package',
        description: `Enable ${pkg.package_type} '${pkg.name}' (${pkg.package_id}) in workspace '${workspaceId}'.`,
        package_id: pkg.package_id,
        required_capabilities: [],
        jobs_to_create: 1,
      });
    }

    // Phase 3: Create agents for agent-type packages
    const agentPackages = requiredPackages.filter((p) => p.package_type === 'agent');
    for (const agent of agentPackages) {
      steps.push({
        step_id: nextStepId(),
        step_type: 'create_agent',
        description: `Create agent instance for '${agent.name}' (${agent.package_id}) in workspace '${workspaceId}'.`,
        package_id: agent.package_id,
        required_capabilities: agent.capabilities,
        jobs_to_create: 1,
      });
    }

    // Phase 4: Initialize workspace resources
    steps.push({
      step_id: nextStepId(),
      step_type: 'initialize_workspace_resource',
      description: `Initialize workspace resources for blueprint '${blueprint.name}' in workspace '${workspaceId}'.`,
      package_id: blueprintId,
      required_capabilities: [],
      jobs_to_create: 1,
    });

    // Phase 5: Initialize memory
    steps.push({
      step_id: nextStepId(),
      step_type: 'initialize_memory',
      description: `Initialize memory and state for blueprint '${blueprint.name}' in workspace '${workspaceId}'.`,
      package_id: blueprintId,
      required_capabilities: [],
      jobs_to_create: 1,
    });

    // Phase 6: Seed the initial signal
    steps.push({
      step_id: nextStepId(),
      step_type: 'seed_signal',
      description: `Seed initial signal to launch blueprint '${blueprint.name}' with inputs: ${blueprint.inputs.join(', ')}.`,
      package_id: blueprintId,
      required_capabilities: [],
      jobs_to_create: 1,
    });

    const estimatedJobs = steps.reduce((sum, s) => sum + s.jobs_to_create, 0);

    const plan: BlueprintLaunchPlan = {
      launch_id: nextPlanId(),
      blueprint_id: blueprintId,
      workspace_id: workspaceId,
      steps,
      required_packages: requiredPackages.map((p) => p.package_id),
      required_backends: compatibleBackends,
      estimated_jobs: estimatedJobs,
      readiness_passed: readinessPassed,
      readiness_failures: readinessFailures,
    };

    this.emitCreated(plan);
    return plan;
  }

  /**
   * Get the ordered list of steps from a launch plan (convenience accessor).
   */
  getSteps(plan: BlueprintLaunchPlan): BlueprintLaunchStep[] {
    return [...plan.steps];
  }

  /**
   * Get steps of a specific type from a launch plan.
   */
  getStepsByType(
    plan: BlueprintLaunchPlan,
    stepType: BlueprintLaunchStepType,
  ): BlueprintLaunchStep[] {
    return plan.steps.filter((s) => s.step_type === stepType);
  }

  // ── Private helpers ───────────────────────────────────────────────────────

  /**
   * Walk the blueprint's dependency tree and collect all required packages
   * in topological order (dependencies before dependents).
   */
  private collectRequiredPackages(blueprint: GhostMartPackage): GhostMartPackage[] {
    const visited = new Set<string>();
    const result: GhostMartPackage[] = [];

    const visit = (packageId: string): void => {
      if (visited.has(packageId)) return;
      visited.add(packageId);

      const pkg = ghostMartPackageStore.getById(packageId);
      if (!pkg) return;

      // Visit dependencies first (topological order)
      for (const depId of pkg.dependencies) {
        visit(depId);
      }

      result.push(pkg);
    };

    for (const depId of blueprint.dependencies) {
      visit(depId);
    }

    return result;
  }

  /**
   * Find packages of a given type that are NOT installed in the workspace.
   */
  private getPackagesToInstall(
    packages: GhostMartPackage[],
    workspaceId: string,
    packageType: string,
  ): GhostMartPackage[] {
    return packages.filter((pkg) => {
      if (pkg.package_type !== packageType) return false;
      const record = workspaceInstallStore.getByWorkspaceAndPackage(workspaceId, pkg.package_id);
      return !record;
    });
  }

  /**
   * Find packages of a given type that are installed but NOT enabled.
   */
  private getPackagesToEnable(
    packages: GhostMartPackage[],
    workspaceId: string,
    packageType: string,
  ): GhostMartPackage[] {
    return packages.filter((pkg) => {
      if (pkg.package_type !== packageType) return false;
      const record = workspaceInstallStore.getByWorkspaceAndPackage(workspaceId, pkg.package_id);
      return record && record.install_status !== 'enabled';
    });
  }

  /**
   * Find backends available for the target workspace.
   */
  private findCompatibleBackends(workspaceId: string): WorkerBackendManifest[] {
    return this.backendRegistry.listBackends().filter((b) => {
      if (b.health_status === 'unavailable') return false;
      if (b.workspace_scope !== null && !b.workspace_scope.includes(workspaceId)) return false;
      return true;
    });
  }

  // ── Event Emission ────────────────────────────────────────────────────────

  private emitCreated(plan: BlueprintLaunchPlan): void {
    eventBus.emit('blueprint.launch_plan.created', plan);
    auditLog.append({
      id: nextPlannerAuditId(),
      eventType: 'blueprint.launch_plan.created',
      objectType: 'BlueprintLaunchPlan',
      objectId: plan.launch_id,
      actorId: 'blueprint-launch-planner',
      timestamp: Date.now(),
      summary: plan.readiness_passed
        ? `Launch plan '${plan.launch_id}' created for blueprint '${plan.blueprint_id}' in workspace '${plan.workspace_id}' — ${plan.steps.length} steps, ${plan.estimated_jobs} estimated jobs.`
        : `Launch plan '${plan.launch_id}' created for blueprint '${plan.blueprint_id}' with readiness failures: ${plan.readiness_failures[0]}`,
      workspaceId: plan.workspace_id,
      metadata: {
        blueprint_id: plan.blueprint_id,
        step_count: plan.steps.length,
        estimated_jobs: plan.estimated_jobs,
        readiness_passed: plan.readiness_passed,
        step_types: [...new Set(plan.steps.map((s) => s.step_type))],
      },
    });
  }

  /**
   * Clear all internal state. For test isolation only.
   */
  reset(): void {
    _nextPlanId = 1;
    _nextStepId = 1;
    _nextPlannerAuditId = 1;
  }
}
